import Head from "next/head";
import { useEffect,useState } from "react";
import { useDispatch } from "react-redux";
import AdminForm from "../components/AdminForm";
import Advertistments from "../components/Advertistments";
import FetchedAdvs from "../components/FetchedAdvs";
import Header from "../components/Header";
import {addToItems} from "../slices/advsSlice";
// import firebase from "../firebase";
//import firebase from 'firebase/app';
// import 'firebase/auth';

export default function Home({advs}) {
  const dispatch=useDispatch();
  
  const addAdvsHandler=()=>{
    // const loadedADvs=[]
    for (const key in advs){
      const loadedadv={
        id:Math.random().toString(16).slice(2),
        image:advs[key].image,
        video:advs[key].video
      }
      dispatch(addToItems(loadedadv))
    }

    
    
  }
  useEffect(()=>{
    addAdvsHandler();
  },[])

  // function addNewAdvHandler(advsData){
  //   fetch("https://penta-value-e37e9-default-rtdb.firebaseio.com/advs.json",{
  //       method:"POST",
  //       body:JSON.stringify(advsData),
  //       headers:{
  //           "Content-Type":"application/json"
  //       }
  //   });
  // } 
  // const handleClick=()=>{
  //   // new firebase.auth.RecaptchaVerifier('recaptcha')
  //   let recaptcha=new firebase.auth.RecaptchaVerifier('recaptcha-container')
  //   console.log(recaptcha);
  // }
  return (
    <div>
      <Head>
        <title>Penta Value</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Header/>
          {/* <button onClick={handleClick}>click me</button> */}
          {/* <AdminForm /> */}
          {/* <FetchedAdvs/> */}
          <Advertistments/>
      </main>
    </div>
  );
}
export async function getServerSideProps(context){
  const request=await fetch("https://signal.creatbots.com/")
  const response=await request.json();
  
  
  return {
    props:{
      advs:response
    }
  }
  
}
